# https://taskfile.dev

version: '2'

env:
  src: /home/istvan/packages/src

tasks:
  vet:
    cmds:
      - go vet
  test:
    cmds:
      - go test ./hash ./path ./repository
  build:
    cmds:
      - go install
  defualt:
    cmds:
      - task: build
