# https://taskfile.dev

version: '2'

tasks:
  vet:
    cmds:
      - go vet
  test:
    cmds:
      - go test ./hash ./path
  build:
    cmds:
      - go install
  defualt:
    cmds:
      - task: build
